<a href="https://colab.research.google.com/github/MaddieMcGreevy/HW1/blob/main/Maddiehw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [1]:
BILLION_SECONDS = 1_000_000_000
SECONDS_IN_A_YEAR = 365.25 * 24 * 60 * 60  # Considering leap years

age = float(input("Enter your age in years: "))

age_in_seconds = age * SECONDS_IN_A_YEAR

if age_in_seconds > BILLION_SECONDS:
    print("You are more than a billion seconds old!")
else:
    print("You are less than a billion seconds old!")



Enter your age in years: 21
You are less than a billion seconds old!


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [2]:
names = ["Connor", "Abby", "Gianna", "Dillon", "Emma", "Aidan", "Sam", "Jane", "Olivia", "Alexis"]

i = 0

while i < len(names):
    print(f"Good morning, {names[i]}!")
    i += 1



Good morning, Connor!
Good morning, Abby!
Good morning, Gianna!
Good morning, Dillon!
Good morning, Emma!
Good morning, Aidan!
Good morning, Sam!
Good morning, Jane!
Good morning, Olivia!
Good morning, Alexis!


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [3]:
numbers = [1, 8, 15, 25, 29, 36, 41, 50, 57, 64, 71, 78, 85, 92, 99]

print("Numbers divisible by 2:")
for num in numbers:
    if num % 2 == 0:
        print(num)



Numbers divisible by 2:
8
36
50
64
78
92


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [6]:
nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

numbers = [3, -7, 2.5, -1.2, 10, -4, 8.8, -6.3, 5, 0]

squared_numbers = []
for num in numbers:
    squared_numbers.append(num ** 2)

print("Squared numbers (longer method):", squared_numbers)


squared_numbers_lc = [num ** 2 for num in numbers]
print("Squared numbers (list comprehension):", squared_numbers_lc)


[0, 1.5625, 251.53959999999998, 625]
Squared numbers (longer method): [9, 49, 6.25, 1.44, 100, 16, 77.44000000000001, 39.69, 25, 0]
Squared numbers (list comprehension): [9, 49, 6.25, 1.44, 100, 16, 77.44000000000001, 39.69, 25, 0]


### Q5. Write a program to print a year if it is a leap year.

In [7]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2025
2025 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [8]:
names = ["Connor", "Abby", "Gianna", "Dillon", "Emma", "Aidan", "Sam", "Jane", "Olivia", "Alexis"]
uppercase_names = [name.upper() for name in names]


print(uppercase_names)

['CONNOR', 'ABBY', 'GIANNA', 'DILLON', 'EMMA', 'AIDAN', 'SAM', 'JANE', 'OLIVIA', 'ALEXIS']


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [12]:
#9
import numpy as np


original = np.random.uniform(1, 1000, 100)
mat_array = original.reshape(20, 5)


sub_array_3_to_10 = mat_array[2:10, :]
print("Sub-array (3rd to 10th rows, all columns):\n", sub_array_3_to_10)


sub_array_last5_last2 = mat_array[-5:, -2:]
print("\nSub-array (last 5 rows, last 2 columns):\n", sub_array_last5_last2)


print("\nDimensions of sub-array (last 5 rows, last 2 columns):", sub_array_last5_last2.shape)


transpose_array = mat_array.T
sub_array_first3_last10 = transpose_array[:3, -10:]
print("\nSub-array (first 3 rows, last 10 columns of transpose_array):\n", sub_array_first3_last10)



Sub-array (3rd to 10th rows, all columns):
 [[109.37466603 780.85505372 171.02779443  63.05593157 766.93606824]
 [429.38553396 239.31739829 660.60123157 934.75950634 988.78111569]
 [727.64797632 897.74084266  69.24897548 392.06884639 267.05768034]
 [731.5310073  318.33550013 253.59920776 548.89703106 877.2842848 ]
 [761.48998725 291.59442505 885.30519325 561.4473415  461.14447393]
 [594.45502104 285.24807698 871.65824255 149.09284986  84.62069864]
 [662.21179441 170.23509624 784.35800368 576.60567079 636.69162304]
 [843.34549317 680.95652155 352.71521989 156.86856476 184.89518287]]

Sub-array (last 5 rows, last 2 columns):
 [[279.35059859 155.29999475]
 [563.89853459 953.79216935]
 [ 42.18118421 717.35324168]
 [446.25085228 193.95911532]
 [952.39079855 628.09230926]]

Dimensions of sub-array (last 5 rows, last 2 columns): (5, 2)

Sub-array (first 3 rows, last 10 columns of transpose_array):
 [[103.32487047 273.35729231 668.40672308 542.10412814 885.82661549
  107.27683282 581.92056994 

In [10]:
#7
import numpy as np


original = np.random.uniform(1, 1000, 100)

largest = np.max(original)
smallest = np.min(original)
mean = np.mean(original)
median = np.median(original)
std_dev = np.std(original)


print(f"Largest Number: {largest}")
print(f"Smallest Number: {smallest}")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")


orig_sqrt = np.sqrt(original)


print("Sample of Square Roots:", orig_sqrt[:10])

Largest Number: 998.359001924217
Smallest Number: 8.185872906941999
Mean: 461.60073905854364
Median: 459.31277816357243
Standard Deviation: 295.09691128778854
Sample of Square Roots: [ 3.51621853 23.0573755  23.37738879 17.47897558 26.54956017  6.97695817
 26.41055722  5.85757106 24.59847697 21.24275203]


In [11]:
#8
import numpy as np

original = np.random.uniform(1, 1000, 100)
mat_array = original.reshape(20, 5)

print("2D Array (mat_array):")
print(mat_array)


column_means = np.mean(mat_array, axis=0)
print("\nMean of each column:", column_means)

row_sums = np.sum(mat_array, axis=1)
print("\nSum of each row:", row_sums.tolist())


transpose_array = mat_array.T

print("\nDimensions of transpose_array:", transpose_array.shape)

transpose_col_means = np.mean(transpose_array, axis=0)
print("\nMean of each column in transpose_array:", transpose_col_means)


transpose_row_sums = np.sum(transpose_array, axis=1)
print("\nSum of each row in transpose_array:", transpose_row_sums)

2D Array (mat_array):
[[743.92974137 320.15503658 554.44368787 508.53916948 763.52682654]
 [356.25779009 282.94334542 232.73859769 346.22141644 754.24573668]
 [351.2212003  796.10565037 786.96751022 781.30060572 162.26158766]
 [728.69115498 110.10965613 923.15523557 225.07041555  57.99948648]
 [124.60263303 556.68174769 262.33342403 598.58646899 800.67086596]
 [160.62935445 459.82295703 329.23444095 599.69518414 336.11937274]
 [777.56127249 916.96977403 289.81071771 617.64950785 431.81123853]
 [436.17835982 434.26093003 143.63159401 648.05444366 560.44511611]
 [811.39928157 249.55159536 952.19194723 438.77538188 352.52189348]
 [113.05590995 597.50584473  72.97355192 360.61841922 187.81854473]
 [377.34199296 822.73792903 692.41302976 987.37222533 343.14254696]
 [918.74049863 977.57001555 821.55438467 621.68633479 452.02783523]
 [673.96154203 174.62371745 758.57301702 739.33002228 145.37884208]
 [446.85561447 485.89810681 744.69110249 166.27396582 224.85327466]
 [918.97945841 568.9271833

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [9]:
# Write your answer here.
import numpy as np
diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan',
        'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']

age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]


menu = [
    'veg. fried rice with whiskey' if (d in ['vegetarian', 'vegan'] and a >= 21) else
    'veg. fried rice with mocktail' if (d in ['vegetarian', 'vegan'] and a < 21) else
    'fish and white wine' if (d == 'pescetarian' and a >= 21) else
    'fish and mocktail' if (d == 'pescetarian' and a < 21) else
    'steak and red wine' if (d in ['keto', 'omnivore'] and a >= 21) else
    'steak and mocktail'  # For keto and omnivore under 21
    for d, a in zip(diet, age)
]


print(menu)



['veg. fried rice with whiskey', 'fish and mocktail', 'veg. fried rice with mocktail', 'steak and red wine', 'fish and white wine', 'steak and mocktail', 'steak and red wine', 'veg. fried rice with whiskey', 'steak and mocktail', 'steak and red wine', 'veg. fried rice with mocktail', 'steak and mocktail', 'steak and red wine', 'veg. fried rice with whiskey', 'veg. fried rice with whiskey']
